version: '3.8'

services:
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: ./back
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 8080:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/src/app
            - /src/app/node_modules
        restart: unless-stopped
    front:
        container_name: nestjs_front_dev
        image: nestjs-front-dev:1.0.0
        build:
            context: ./thiyomi
            target: development
            dockerfile: ./Dockerfile
        command: npm run start
        ports:
            - 3000:8080
        networks:
            - nesjs-network
        volumes:
            - .:/src/app
            - /src/app/node_modules
        restart: unless-stopped
networks:
    nesjs-network: